// Curated list of Lucide icon names useful for a self-hosted service hub
const ICON_LIST = [
    "activity", "airplay", "alert-triangle", "archive", "at-sign",
    "bar-chart-3", "battery", "bell", "bluetooth", "book", "bookmark",
    "box", "briefcase", "bug", "building", "calendar", "camera",
    "chart-pie", "check-circle", "chrome", "circle-dot", "clipboard",
    "clock", "cloud", "cloud-download", "cloud-upload", "code", "code-2",
    "cog", "command", "compass", "container", "cpu", "credit-card",
    "database", "desktop", "disc", "download", "droplet",
    "edit", "eye", "file", "file-code", "file-text", "film",
    "filter", "flag", "flame", "folder", "folder-open",
    "gamepad-2", "gauge", "gift", "git-branch", "git-commit",
    "git-merge", "git-pull-request", "github", "gitlab", "globe",
    "grid", "hard-drive", "hash", "headphones", "heart", "home",
    "image", "inbox", "info", "key", "lamp", "laptop",
    "layers", "layout", "layout-dashboard", "library", "life-buoy",
    "link", "list", "lock", "log-in", "log-out",
    "mail", "map", "map-pin", "megaphone", "message-circle",
    "message-square", "mic", "monitor", "moon", "mouse",
    "music", "navigation", "network", "package", "paintbrush",
    "palette", "panel-left", "paperclip", "pen", "phone",
    "pie-chart", "play", "plug", "plus", "podcast", "power",
    "printer", "puzzle", "qr-code", "radio", "refresh-cw",
    "rocket", "rss", "ruler", "save", "scan", "search",
    "send", "server", "settings", "share-2", "shield",
    "shield-check", "shopping-bag", "shopping-cart", "signal",
    "sliders", "smartphone", "smile", "speaker", "star",
    "sun", "table", "tablet", "tag", "target", "terminal",
    "thermometer", "timer", "toggle-left", "tool", "trash-2",
    "trending-up", "trophy", "truck", "tv", "type",
    "umbrella", "upload", "user", "users", "video",
    "voicemail", "volume-2", "wallet", "wand-2", "watch",
    "wifi", "wind", "wrench", "zap"
];
